github: [metadata]
plugins:
  - jekyll-feed

url: http://projectrobotplayground.com
title: 'Project: Robot Playground'
author: Allison Thackston
description: >  
  'A curated set of assets for robotic simulation.'
copyright: 'Copyright &copy; 2019 Allison Thackston. All Rights Reserved.'
google_analytics: 'UA-131243656-2'
